### PR TITLE
Removed scrolled title from nav bar

### LINKED ISSUE #307: Language change icon is not displayed in the menu
**Describe the bug**
On the "Unterstützen" page, the language change icon is not displayed in the menu. Only on the German page!

**Reproduce**
Screenshot 2021-10-31 094725

### PR DESCRIPTION
**Pull request by ClientCrash**
Closes #307

### CODE REVIEW

**Comment by ClientCrash** [comment]
The title is always hidden with css so we can just remove it. This fixes the issue where the language icon is pushed out of view by the long (and hidden) title.

**Review by DevMimas — APPROVED** [review]

**Review by MarcelCoding — CHANGES_REQUESTED** [review]
Please also remove the corresponding css.

**Comment by ClientCrash** [comment]
> Please also remove the corresponding css.

Done

**Review by MarcelCoding — APPROVED** [review]
The title was actually not hidden. The opacity was set so `1` if the page was scrolled. But the title bar has not so many entries that there is no space left. So removing the title is for me ok.

**Review by DevMimas — APPROVED** [review]

**Pull request merged**
