### PR TITLE
changed how blog date is written out

### PR DESCRIPTION
**Pull request by Mondmarmelade**
**Description**
> changed how blog date is displayed
image

**Issue**
#324

### CODE REVIEW

**Comment by MarcelCoding** [comment]
This isn't any more language-specific!

**Comment by MarcelCoding** [comment]
We should be switching to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat because there you can specify a language and not like the old version on the browser language-oriented.

**Comment by Mondmarmelade** [comment]
@MarcelCoding Moment.js would also be an option.

**Comment by MarcelCoding** [comment]
No, because it is not tree-shakeable and there are better native implementations.

**Pull request closed without merging**
