### PR TITLE
Fixed line break as requested by @DevMimas

### LINKED ISSUE #283: Index page displays version number over multiple lines.
changes requested by @DevMimas

### PR DESCRIPTION
**Pull request by ClientCrash**
@DevMimas 

**Issue**
Closes #283

### CODE REVIEW

**Comment by MarcelCoding** [comment]
image

**Review by DevMimas — DISMISSED** [review]

**Review by MarcelCoding — CHANGES_REQUESTED** [review]
image

**Comment by ClientCrash** [comment]
Please test it again with Firefox and chrome. Only merge if it works with both browser. I can not test my changes right now.

**Comment by MarcelCoding** [comment]
Just don't do inline CSS use a class. Scss code uses an auto prefixer witch adds prefixed for all browsers. There are still prefixes for browsers not covered.

**Comment by ClientCrash** [comment]
I will work on this once I get home.

**Review by MarcelCoding — APPROVED** [review]
Now it works. 
image
There is also one more prefix for webkit.

**Review by DevMimas — APPROVED** [review]

**Pull request merged**
