### PR TITLE
fix Discord invite link

### PR DESCRIPTION
**Pull request by TheBlckbird**
**Description**
The Discord invite link is invalid so I fixed it

### CODE REVIEW

**Comment by TheBlckbird** [comment]
tests are failing (not because of my code…)

**Comment by Tristan-H11** [comment]
> tests are failing (not because of my code…)

The tests fail, because the linter found some formatting errors. You changed a bit more then just the invite link.

**Comment by TheBlckbird** [comment]
oh, I see

**Comment by TheBlckbird** [comment]
ill open a new PR, I dont know how to revert these things...

**Pull request closed without merging**
